
package wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Michael", targetNamespace = "http://web/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Michael {


    /**
     * 
     * @param gX
     * @param gY
     * @param gZ
     * @param xml
     * @param apX
     * @param ld
     * @param apZ
     * @param apY
     * @param pl1M
     * @param apPt
     * @param n
     * @param conc
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculate", targetNamespace = "http://web/", className = "wsdl.Calculate")
    @ResponseWrapper(localName = "calculateResponse", targetNamespace = "http://web/", className = "wsdl.CalculateResponse")
    @Action(input = "http://web/Michael/calculateRequest", output = "http://web/Michael/calculateResponse")
    public Double calculate(
        @WebParam(name = "g_x", targetNamespace = "")
        Integer gX,
        @WebParam(name = "g_y", targetNamespace = "")
        Integer gY,
        @WebParam(name = "g_z", targetNamespace = "")
        Integer gZ,
        @WebParam(name = "ap_x", targetNamespace = "")
        Integer apX,
        @WebParam(name = "ap_y", targetNamespace = "")
        Integer apY,
        @WebParam(name = "ap_z", targetNamespace = "")
        Integer apZ,
        @WebParam(name = "ap_pt", targetNamespace = "")
        Integer apPt,
        @WebParam(name = "n", targetNamespace = "")
        Double n,
        @WebParam(name = "PL_1m", targetNamespace = "")
        Double pl1M,
        @WebParam(name = "ld", targetNamespace = "")
        Double ld,
        @WebParam(name = "conc", targetNamespace = "")
        Double conc,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

}
